In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../Data/Raw/US_Accidents_March23_sampled_500k.csv")

df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-2047758,Source2,2,2019-06-12 10:10:56,2019-06-12 10:55:58,30.641211,-91.153481,NaN,NaN,0.000,...,False,False,False,False,True,False,Day,Day,Day,Day
1,A-4694324,Source1,2,2022-12-03 23:37:14.000000000,2022-12-04 01:56:53.000000000,38.990562,-77.399070,38.990037,-77.398282,0.056,...,False,False,False,False,False,False,Night,Night,Night,Night
2,A-5006183,Source1,2,2022-08-20 13:13:00.000000000,2022-08-20 15:22:45.000000000,34.661189,-120.492822,34.661189,-120.492442,0.022,...,False,False,False,False,True,False,Day,Day,Day,Day
3,A-4237356,Source1,2,2022-02-21 17:43:04,2022-02-21 19:43:23,43.680592,-92.993317,43.680574,-92.972223,1.054,...,False,False,False,False,False,False,Day,Day,Day,Day
4,A-6690583,Source1,2,2020-12-04 01:46:00,2020-12-04 04:13:09,35.395484,-118.985176,35.395476,-118.985995,0.046,...,False,False,False,False,False,False,Night,Night,Night,Night

In [2]:
missing = (
    df.isnull().sum()
      .sort_values(ascending=False)
)

missing[missing > 0]

End_Lng                  220377
End_Lat                  220377
Precipitation(in)        142616
Wind_Chill(F)            129017
Wind_Speed(mph)           36987
Visibility(mi)            11291
Wind_Direction            11197
Humidity(%)               11130
Weather_Condition         11101
Temperature(F)            10466
Pressure(in)               8928
Weather_Timestamp          7674
Sunrise_Sunset             1483
Civil_Twilight             1483
Astronomical_Twilight      1483
Nautical_Twilight          1483
Airport_Code               1446
Street                      691
Timezone                    507
Zipcode                     116
City                         19
Description                   1
dtype: int64

In [3]:
df.duplicated().sum()

np.int64(0)

In [4]:
df.drop_duplicates(inplace=True)

In [7]:
df["Start_Time"] = pd.to_datetime(df["Start_Time"])
df["End_Time"] = pd.to_datetime(df["End_Time"])

In [8]:
df["Year"] = df["Start_Time"].dt.year

df["Month"] = df["Start_Time"].dt.month_name()

df["Day"] = df["Start_Time"].dt.day_name()

df["Hour"] = df["Start_Time"].dt.hour

df["Weekday"] = df["Start_Time"].dt.weekday

In [9]:
df.to_csv(
    "../Data/Processed/US_Accidents_Cleaned.csv",
    index=False
)

In [10]:
df["Month_No"] = df["Start_Time"].dt.month
df["Month"] = df["Start_Time"].dt.month_name()

In [3]:
df["Start_Time"].dtype

In [14]:
df[["Start_Time","Year","Month_No","Month","Day","Hour","Weekday"]].head()

           Start_Time  Year  Month_No     Month        Day  Hour  Weekday
0 2019-06-12 10:10:56  2019         6      June  Wednesday    10        2
1 2022-12-03 23:37:14  2022        12  December   Saturday    23        5
2 2022-08-20 13:13:00  2022         8    August   Saturday    13        5
3 2022-02-21 17:43:04  2022         2  February     Monday    17        0
4 2020-12-04 01:46:00  2020        12  December     Friday     1        4

In [15]:
df.to_csv(
    "../Data/Processed/US_Accidents_Cleaned.csv",
    index=False
)