In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Data/Processed/US_Accidents_Cleaned.csv")

df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,Year,Month,Day,Hour,Weekday,Month_No
0,A-2047758,Source2,2,2019-06-12 10:10:56,2019-06-12 10:55:58,30.641211,-91.153481,NaN,NaN,0.000,...,Day,Day,Day,Day,2019,June,Wednesday,10,2,6
1,A-4694324,Source1,2,2022-12-03 23:37:14,2022-12-04 01:56:53,38.990562,-77.399070,38.990037,-77.398282,0.056,...,Night,Night,Night,Night,2022,December,Saturday,23,5,12
2,A-5006183,Source1,2,2022-08-20 13:13:00,2022-08-20 15:22:45,34.661189,-120.492822,34.661189,-120.492442,0.022,...,Day,Day,Day,Day,2022,August,Saturday,13,5,8
3,A-4237356,Source1,2,2022-02-21 17:43:04,2022-02-21 19:43:23,43.680592,-92.993317,43.680574,-92.972223,1.054,...,Day,Day,Day,Day,2022,February,Monday,17,0,2
4,A-6690583,Source1,2,2020-12-04 01:46:00,2020-12-04 04:13:09,35.395484,-118.985176,35.395476,-118.985995,0.046,...,Night,Night,Night,Night,2020,December,Friday,1,4,12

In [3]:
df.shape

(500000, 52)

In [4]:
df.isnull().sum()

ID                            0
Source                        0
Severity                      0
Start_Time                    0
End_Time                      0
Start_Lat                     0
Start_Lng                     0
End_Lat                  220377
End_Lng                  220377
Distance(mi)                  0
Description                   1
Street                      691
City                         19
County                        0
State                         0
Zipcode                     116
Country                       0
Timezone                    507
Airport_Code               1446
Weather_Timestamp          7674
Temperature(F)            10466
Wind_Chill(F)            129017
Humidity(%)               11130
Pressure(in)               8928
Visibility(mi)            11291
Wind_Direction            11197
Wind_Speed(mph)           36987
Precipitation(in)        142616
Weather_Condition         11101
Amenity                       0
Bump                          0
Crossing                      0
Give_Way                      0
Junction                      0
No_Exit                       0
Railway                       0
Roundabout                    0
Station                       0
Stop                          0
Traffic_Calming               0
Traffic_Signal                0
Turning_Loop                  0
Sunrise_Sunset             1483
Civil_Twilight             1483
Nautical_Twilight          1483
Astronomical_Twilight      1483
Year                          0
Month                         0
Day                           0
Hour                          0
Weekday                       0
Month_No                      0
dtype: int64

In [5]:
columns = [
    "Severity",
    "Start_Time",
    "Year",
    "Month_No",
    "Month",
    "Day",
    "Hour",
    "Weekday",
    "State",
    "City",
    "County",
    "Temperature(F)",
    "Humidity(%)",
    "Visibility(mi)",
    "Wind_Speed(mph)",
    "Weather_Condition",
    "Sunrise_Sunset",
    "Distance(mi)",
    "Amenity",
    "Bump",
    "Crossing",
    "Give_Way",
    "Junction",
    "No_Exit",
    "Railway",
    "Roundabout",
    "Station",
    "Stop",
    "Traffic_Calming",
    "Traffic_Signal",
    "Turning_Loop"
]

df = df[columns]

In [6]:
df.head()

,Severity,Start_Time,Year,Month_No,Month,Day,Hour,Weekday,State,City,...,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop
0,2,2019-06-12 10:10:56,2019,6,June,Wednesday,10,2,LA,Zachary,...,False,False,False,False,False,False,False,False,True,False
1,2,2022-12-03 23:37:14,2022,12,December,Saturday,23,5,VA,Sterling,...,False,False,False,False,False,False,False,False,False,False
2,2,2022-08-20 13:13:00,2022,8,August,Saturday,13,5,CA,Lompoc,...,False,False,False,False,False,False,False,False,True,False
3,2,2022-02-21 17:43:04,2022,2,February,Monday,17,0,MN,Austin,...,False,False,False,False,False,False,False,False,False,False
4,2,2020-12-04 01:46:00,2020,12,December,Friday,1,4,CA,Bakersfield,...,False,False,False,False,False,False,False,False,False,False

In [7]:
df.shape

(500000, 31)

In [8]:
df.isnull().sum()

Severity                 0
Start_Time               0
Year                     0
Month_No                 0
Month                    0
Day                      0
Hour                     0
Weekday                  0
State                    0
City                    19
County                   0
Temperature(F)       10466
Humidity(%)          11130
Visibility(mi)       11291
Wind_Speed(mph)      36987
Weather_Condition    11101
Sunrise_Sunset        1483
Distance(mi)             0
Amenity                  0
Bump                     0
Crossing                 0
Give_Way                 0
Junction                 0
No_Exit                  0
Railway                  0
Roundabout               0
Station                  0
Stop                     0
Traffic_Calming          0
Traffic_Signal           0
Turning_Loop             0
dtype: int64

In [9]:
numeric_cols = [
    "Temperature(F)",
    "Humidity(%)",
    "Visibility(mi)",
    "Wind_Speed(mph)"
]

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [10]:
categorical_cols = [
    "Weather_Condition",
    "Sunrise_Sunset"
]

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [11]:
df["City"] = df["City"].fillna("Unknown")

In [12]:
df.isnull().sum()

Severity             0
Start_Time           0
Year                 0
Month_No             0
Month                0
Day                  0
Hour                 0
Weekday              0
State                0
City                 0
County               0
Temperature(F)       0
Humidity(%)          0
Visibility(mi)       0
Wind_Speed(mph)      0
Weather_Condition    0
Sunrise_Sunset       0
Distance(mi)         0
Amenity              0
Bump                 0
Crossing             0
Give_Way             0
Junction             0
No_Exit              0
Railway              0
Roundabout           0
Station              0
Stop                 0
Traffic_Calming      0
Traffic_Signal       0
Turning_Loop         0
dtype: int64

In [13]:
df.to_csv(
    "../Data/Processed/PowerBI_Dataset.csv",
    index=False
)